public class FieldCompliance
{

 public String SendingRepName{ get ;set;}
 public String SendingRepStreet { get ;set;}
 public String SendingRepCity { get ;set;}
 public String SendingRepState{ get ;set;}
 public String SendingRepZip{ get ;set;}
 public String ReceivingRepName{ get ;set;}
 public String ReceivingRepStreet{ get ;set;}
 public String ReceivingRepCity{ get ;set;}
 public String ReceivingRepState{ get ;set;}
 public String ReceivingRepZip{ get ;set;}
 public String TransactionType{ get ;set;}
 
 
 
 }